In [15]:
import numpy as np

def arrays(arr):
  return np.array(arr[::-1],float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

3 4 -5
[-5.  4.  3.]


In [17]:
import numpy as np

np.set_printoptions(sign=' ')

arr = np.array(input().split(),float)

print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

4.5 6.5
[ 4.  6.]
[ 5.  7.]
[ 4.  6.]


In [19]:
import numpy as np

n,m = input().split()

arr = []
for i in range(int(n)):
  arr.append(np.array(input().split(),int))

arr2 = np.sum(arr, axis = 0)

print (np.prod(arr2)) 

2 2
1 2
3 4
24


In [13]:
import numpy as np

n,m = input().strip().split()

lst = []

for i in range(int(n)):
  arr = input().strip().split()
  lst.append(arr)

arr2 = np.array(lst,int)

print(arr2.transpose())
print(arr2.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]
