In [6]:
import numpy as np
arr = np.arange(10)
arr
#np.sqrt(arr)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result = [(x if c else y)
  for x, y, c in zip(xarr, yarr, cond)]
result

result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [17]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr)

array([[-0.16451444,  2.        ,  2.        ,  2.        ],
       [-0.54215566, -0.89604069,  2.        , -1.85923027],
       [-0.95887845,  2.        ,  2.        , -0.13882885],
       [ 2.        ,  2.        , -0.42688742, -1.67876518]])

In [18]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())

[[-0.25347094  0.91768217 -1.61745886  0.31578468]
 [-1.09274184  0.64036335 -0.44325098  0.32114232]
 [ 0.89918494  0.35882573  0.11114037 -0.34451593]
 [-0.94235233  0.62856354 -0.83299406 -1.25517341]
 [-1.60169264 -1.51411362  0.45912583  0.49679536]]
-0.23745781629157015
-0.23745781629157015
-4.749156325831403


In [20]:
arr = np.random.randn(6)
arr
arr.sort()
arr

array([-1.4231132 , -1.21197665, -0.97621832,  0.1989128 ,  2.18906449,
        3.02750539])